# Generated by Django 5.1.1 on 2024-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to='media/article_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default=1, upload_to='media/article_audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=1, upload_to='media/article_video'),
            preserve_default=False,
        ),
    ]
